languageCode: en-us
title: Vincent Carrier, Web Developer
relativeURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute: true
  highlight:
    style: tango
    lineNos: false
    noClasses: false
