[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.processing.html]
  minify = true

[build.processing.images]
  compress = true

[context.production.environment]
  HUGO_VERSION = "0.79.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
   # optional, fails build when a category is below a threshold
   [plugins.inputs.thresholds]
     performance = 0.9
     accessibility = 0.9
     best-practices = 0.9

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
